# This workflow will merge pull requests automatically
#

name: automerge
on:
  check_suite:
    types:
      - completed

jobs:
  automerge:
    if: github.event.check_suite.app.name == 'Azure Pipelines' &&  github.event.check_suite.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
    - name: automerge
      uses: 'xumia/automerge-action@v0.13.1.1'
      with:
        args: "--trace"
      env:
        GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        MERGE_LABELS: 'automerge'
        MERGE_METHOD: 'squash'
        MERGE_FILTER_AUTHOR: 'MiaoXuHui'
        MERGE_DELETE_BRANCH: true
